spring.application.name=ecomarket-spa

spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/db_ecomarket}
spring.datasource.username=${DB_USERNAME:ecomarket_user}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
